# Generated by Django 4.1.6 on 2023-02-20 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("conference_rooms_booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conferenceroom",
            name="capacity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="conferenceroom",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="conferenceroom",
            name="projector_availability",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BookingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("comment", models.TextField(null=True)),
                (
                    "room_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conference_rooms_booking.conferenceroom",
                    ),
                ),
            ],
            options={
                "unique_together": {("room_id", "date")},
            },
        ),
    ]
